<?php

module_load_include('inc', 'custom_services', 'resources.inc');

function custom_services_services_resources() {
  return array(
    'content' => array(
      'retrieve' => array(
        'callback' => '_content_retrieve',
        'access callback' => '_custom_services_access',
        'access arguments' => array('retrieve'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'id',
            'type' => 'int',
            'description' => 'Identificador del contenido',
            'source' => array('path' => '0'),
            'optional' => FALSE,
          ),
        ),
        'help' => t('Return content.'),
      ),
    ),
  );
}

function _custom_services_access($op, $args) {
  return true;
}